name: Live 05 CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn ci:lint

      - name: Run type checks
        run: yarn typecheck

      - name: Run tests
        run: yarn ci:test
